<a href="https://colab.research.google.com/github/samikshagadhave/binary_classification/blob/main/Copy_of_incorrect_to_correct_ones_in_efficientnetB1_by_image_processing_method.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount("/content/gdrive")

Mounted at /content/gdrive


In [ ]:
%cd /content/gdrive

/content/gdrive


In [ ]:
import pandas as pd

df=pd.read_excel(r'/content/gdrive/MyDrive/dataset/T51+T52BAD+T53BAD+T54BAD+T57BAD +T58BAD/Train 1.xlsx')

df['OR_Gate']=df['Tower']|df['Transmission line']|df['insulator']|df['vibration damper']
#print(df['OR_Gate'])

Bad_dataset=list(df[df['OR_Gate']==0]["Image Name"])
#print(Bad_dataset)

Good_dataset=list(df[df['OR_Gate']==1]["Image Name"])
#print(Good_dataset)
path=r"/content/gdrive/MyDrive/dataset/T51+T52BAD+T53BAD+T54BAD+T57BAD +T58BAD/train/"

img_path_Bad_dataset=r"/content/gdrive/MyDrive/dataset/T51+T52BAD+T53BAD+T54BAD+T57BAD +T58BAD/Train/bad_dataset/"

img_path_Good_dataset =r"/content/gdrive/MyDrive/dataset/T51+T52BAD+T53BAD+T54BAD+T57BAD +T58BAD/Train/good_dataset/"
import shutil
for i in Bad_dataset:
   src_path=path+i
   #print(src_path)
   dest_path=img_path_Bad_dataset+i
   #print(dest_path)
   temp=shutil.copy(src_path,dest_path)
   #print(temp)
   print("bad_dataset folder created and relevant images have been moved")
for i in Good_dataset:
   src_path=path+i
   #print(src_path)
   dest_path=img_path_Good_dataset+i
   #print(dest_path)
   temp=shutil.copy(src_path, dest_path)
   print("good_dataset folder created and relevant images have been moved")


df=pd.read_excel(r'/content/gdrive/MyDrive/dataset/T51+T52BAD+T53BAD+T54BAD+T57BAD +T58BAD/Test 1.xlsx')

df['OR_Gate']=df['Tower']|df['Transmission line']|df['insulator']|df['vibration damper']
#print(df['OR_Gate'])

Bad_dataset=list(df[df['OR_Gate']==0]["Image Name"])
Good_dataset=list(df[df['OR_Gate']==1]["Image Name"])
#print(Good_dataset)
path=r"/content/gdrive/MyDrive/dataset/T51+T52BAD+T53BAD+T54BAD+T57BAD +T58BAD/test/"

img_path_Bad_dataset=r"/content/gdrive/MyDrive/dataset/T51+T52BAD+T53BAD+T54BAD+T57BAD +T58BAD/Test/bad_dataset/"
img_path_Good_dataset =r"/content/gdrive/MyDrive/dataset/T51+T52BAD+T53BAD+T54BAD+T57BAD +T58BAD/Test/good_dataset/"
import shutil
for i in Bad_dataset:
   src_path=path+i
   #print(src_path)
   dest_path=img_path_Bad_dataset+i
   #print(dest_path)
   temp=shutil.copy(src_path,dest_path)
   #print(temp)
   print("bad_dataset folder created and relevant images have been moved")
for i in Good_dataset:
   src_path=path+i
   #print(src_path)
   dest_path=img_path_Good_dataset+i
   #print(dest_path)
   temp=shutil.copy(src_path, dest_path)
   print("good_dataset folder created and relevant images have been moved")


bad_dataset folder created and relevant images have been moved
bad_dataset folder created and relevant images have been moved
bad_dataset folder created and relevant images have been moved
bad_dataset folder created and relevant images have been moved
bad_dataset folder created and relevant images have been moved
bad_dataset folder created and relevant images have been moved
bad_dataset folder created and relevant images have been moved
bad_dataset folder created and relevant images have been moved
bad_dataset folder created and relevant images have been moved
bad_dataset folder created and relevant images have been moved
bad_dataset folder created and relevant images have been moved
bad_dataset folder created and relevant images have been moved
bad_dataset folder created and relevant images have been moved
bad_dataset folder created and relevant images have been moved
bad_dataset folder created and relevant images have been moved
bad_dataset folder created and relevant images have bee

In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import Input, Lambda, Dense, Flatten,Dropout,Conv2D,GlobalAveragePooling2D
from tensorflow.keras.models import Model
from tensorflow.keras.preprocessing import image
from tensorflow.keras.models import Sequential
import numpy as np
import pandas as pd
import os
import cv2
import matplotlib.pyplot as plt

train_ds=keras.utils.image_dataset_from_directory(
    directory=r'/content/gdrive/MyDrive/dataset/T51+T52BAD+T53BAD+T54BAD+T57BAD +T58BAD/Train',
    labels='inferred',
    label_mode='int',
    batch_size=4,
    image_size=(240,240)
)
validation_ds=keras.utils.image_dataset_from_directory(
    directory=r'/content/gdrive/MyDrive/dataset/T51+T52BAD+T53BAD+T54BAD+T57BAD +T58BAD/Test',
    labels='inferred',
    label_mode='int',
    batch_size=4,
    image_size=(240,240)
)
print(train_ds)
print(validation_ds)
from tensorflow.keras.applications import EfficientNetB1
model=EfficientNetB1(weights='imagenet',include_top=False,input_shape=(240,240,3))
my_model=Sequential([model,
                     Conv2D(1024,3,1,activation='relu'),
                     GlobalAveragePooling2D(),
                     Dense(1024,activation='relu'),
                     Dropout(0.2),
                     Dense(1024,activation='relu'),
                     Dropout(0.2),
                     Dense(1,activation='sigmoid'),
                     ])
my_model.summary()

Found 198 files belonging to 2 classes.
Found 86 files belonging to 2 classes.
<_BatchDataset element_spec=(TensorSpec(shape=(None, 240, 240, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None,), dtype=tf.int32, name=None))>
<_BatchDataset element_spec=(TensorSpec(shape=(None, 240, 240, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None,), dtype=tf.int32, name=None))>
27018416/27018416 [==============================] - 0s 0us/step
Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 efficientnetb1 (Functional)  (None, 8, 8, 1280)       6575239   
                                                                 
 conv2d (Conv2D)             (None, 6, 6, 1024)        11797504  
                                                                 
 global_average_pooling2d (G  (None, 1024)             0         
 lobalAveragePooling2D)                                          
    

In [ ]:
train_ds=train_ds.prefetch(tf.data.AUTOTUNE)
train_ds

<_PrefetchDataset element_spec=(TensorSpec(shape=(None, 240, 240, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None,), dtype=tf.int32, name=None))>

In [ ]:
validation_ds=validation_ds.prefetch(tf.data.AUTOTUNE)
validation_ds

<_PrefetchDataset element_spec=(TensorSpec(shape=(None, 240, 240, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None,), dtype=tf.int32, name=None))>

In [ ]:
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import BinaryCrossentropy
from tensorflow.keras import metrics
metrics=['accuracy']
my_model.compile(loss=BinaryCrossentropy(),optimizer=Adam(learning_rate=0.001),metrics=metrics)

In [ ]:
history=my_model.fit(train_ds,epochs=30,validation_data=validation_ds)

Epoch 1/30
50/50 [==============================] - 97s 468ms/step - loss: 1.6264 - accuracy: 0.9040 - val_loss: 0.8145 - val_accuracy: 0.6744
Epoch 2/30
50/50 [==============================] - 24s 439ms/step - loss: 0.6265 - accuracy: 0.8889 - val_loss: 2.8498 - val_accuracy: 0.7442
Epoch 3/30
50/50 [==============================] - 23s 415ms/step - loss: 0.0851 - accuracy: 0.9747 - val_loss: 2.2606 - val_accuracy: 0.5814
Epoch 4/30
50/50 [==============================] - 26s 489ms/step - loss: 0.4036 - accuracy: 0.9293 - val_loss: 2.4747 - val_accuracy: 0.8023
Epoch 5/30
50/50 [==============================] - 26s 493ms/step - loss: 0.0515 - accuracy: 0.9848 - val_loss: 0.9564 - val_accuracy: 0.6512
Epoch 6/30
50/50 [==============================] - 23s 429ms/step - loss: 0.1285 - accuracy: 0.9646 - val_loss: 0.6587 - val_accuracy: 0.8488
Epoch 7/30
50/50 [==============================] - 23s 425ms/step - loss: 0.0319 - accuracy: 0.9798 - val_loss: 1.9643 - val_accuracy: 0.7093

In [ ]:
from PIL import Image
import matplotlib.pyplot as plt
image=Image.open('/content/gdrive/MyDrive/dataset/T51+T52BAD+T53BAD+T54BAD+T57BAD +T58BAD/Test/bad_dataset/DJI_0489.jpg')
print(type(image))
print(image.mode)
print(image.format)


<class 'PIL.JpegImagePlugin.JpegImageFile'>
RGB
JPEG


In [ ]:
from PIL import Image
import matplotlib.pyplot as plt
image=Image.open('/content/gdrive/MyDrive/dataset/T51+T52BAD+T53BAD+T54BAD+T57BAD +T58BAD/Test/bad_dataset/DJI_0491.jpg')
print(type(image))
print(image.mode)
print(image.format)


<class 'PIL.JpegImagePlugin.JpegImageFile'>
RGB
JPEG


In [ ]:
from PIL import Image
import matplotlib.pyplot as plt
image=Image.open('/content/gdrive/MyDrive/dataset/T51+T52BAD+T53BAD+T54BAD+T57BAD +T58BAD/Test/bad_dataset/DJI_0493.jpg')
print(type(image))
print(image.mode)
print(image.format)


<class 'PIL.JpegImagePlugin.JpegImageFile'>
RGB
JPEG


In [ ]:
from PIL import Image
import matplotlib.pyplot as plt
image=Image.open('/content/gdrive/MyDrive/dataset/T51+T52BAD+T53BAD+T54BAD+T57BAD +T58BAD/Test/bad_dataset/DJI_0495.jpg')
print(type(image))
print(image.mode)
print(image.format)


<class 'PIL.JpegImagePlugin.JpegImageFile'>
RGB
JPEG


In [ ]:
from PIL import Image
import matplotlib.pyplot as plt
image=Image.open('/content/gdrive/MyDrive/dataset/T51+T52BAD+T53BAD+T54BAD+T57BAD +T58BAD/Test/bad_dataset/DJI_0497.jpg')
print(type(image))
print(image.mode)
print(image.format)


<class 'PIL.JpegImagePlugin.JpegImageFile'>
RGB
JPEG


In [ ]:
from PIL import Image
import matplotlib.pyplot as plt
image=Image.open('/content/gdrive/MyDrive/dataset/T51+T52BAD+T53BAD+T54BAD+T57BAD +T58BAD/Test/bad_dataset/DJI_0501.jpg')
print(type(image))
print(image.mode)
print(image.format)


<class 'PIL.JpegImagePlugin.JpegImageFile'>
RGB
JPEG


In [ ]:
from PIL import Image
import matplotlib.pyplot as plt
image=Image.open('/content/gdrive/MyDrive/dataset/T51+T52BAD+T53BAD+T54BAD+T57BAD +T58BAD/Test/bad_dataset/DJI_0503.jpg')
print(type(image))
print(image.mode)
print(image.format)


<class 'PIL.JpegImagePlugin.JpegImageFile'>
RGB
JPEG


In [ ]:
from PIL import Image
import matplotlib.pyplot as plt
image=Image.open('/content/gdrive/MyDrive/dataset/T51+T52BAD+T53BAD+T54BAD+T57BAD +T58BAD/Test/bad_dataset/DJI_0503.jpg')
print(type(image))
print(image.mode)
print(image.format)


<class 'PIL.JpegImagePlugin.JpegImageFile'>
RGB
JPEG


In [ ]:
from PIL import Image
import matplotlib.pyplot as plt
image=Image.open('/content/gdrive/MyDrive/dataset/T51+T52BAD+T53BAD+T54BAD+T57BAD +T58BAD/Test/bad_dataset/DJI_0505.jpg')
print(type(image))
print(image.mode)
print(image.format)


<class 'PIL.JpegImagePlugin.JpegImageFile'>
RGB
JPEG


In [ ]:
from PIL import Image
import matplotlib.pyplot as plt
image=Image.open('/content/gdrive/MyDrive/dataset/T51+T52BAD+T53BAD+T54BAD+T57BAD +T58BAD/Test/bad_dataset/DJI_0507.jpg')
print(type(image))
print(image.mode)
print(image.format)


<class 'PIL.JpegImagePlugin.JpegImageFile'>
RGB
JPEG


In [ ]:
from PIL import Image
import matplotlib.pyplot as plt
image=Image.open('/content/gdrive/MyDrive/dataset/T51+T52BAD+T53BAD+T54BAD+T57BAD +T58BAD/Test/bad_dataset/DJI_0509.jpg')
print(type(image))
print(image.mode)
print(image.format)


<class 'PIL.JpegImagePlugin.JpegImageFile'>
RGB
JPEG


In [ ]:
from PIL import Image
import matplotlib.pyplot as plt
image=Image.open('/content/gdrive/MyDrive/dataset/T51+T52BAD+T53BAD+T54BAD+T57BAD +T58BAD/Test/bad_dataset/DJI_0976.jpg')
print(type(image))
print(image.mode)
print(image.format)


<class 'PIL.JpegImagePlugin.JpegImageFile'>
RGB
JPEG


In [ ]:
from PIL import Image
import matplotlib.pyplot as plt
image=Image.open('/content/gdrive/MyDrive/dataset/T51+T52BAD+T53BAD+T54BAD+T57BAD +T58BAD/Test/bad_dataset/DJI_0978.jpg')
print(type(image))
print(image.mode)
print(image.format)


<class 'PIL.JpegImagePlugin.JpegImageFile'>
RGB
JPEG


In [ ]:
from PIL import Image
import matplotlib.pyplot as plt
image=Image.open('/content/gdrive/MyDrive/dataset/T51+T52BAD+T53BAD+T54BAD+T57BAD +T58BAD/Test/bad_dataset/DJI_0980.jpg')
print(type(image))
print(image.mode)
print(image.format)


<class 'PIL.JpegImagePlugin.JpegImageFile'>
RGB
JPEG


In [ ]:
from PIL import Image
import matplotlib.pyplot as plt
image=Image.open('/content/gdrive/MyDrive/dataset/T51+T52BAD+T53BAD+T54BAD+T57BAD +T58BAD/Test/bad_dataset/DJI_0982.jpg')
print(type(image))
print(image.mode)
print(image.format)


<class 'PIL.JpegImagePlugin.JpegImageFile'>
RGB
JPEG


In [ ]:
from PIL import Image
import matplotlib.pyplot as plt
image=Image.open('/content/gdrive/MyDrive/dataset/T51+T52BAD+T53BAD+T54BAD+T57BAD +T58BAD/Test/bad_dataset/DJI_0984.jpg')
print(type(image))
print(image.mode)
print(image.format)


<class 'PIL.JpegImagePlugin.JpegImageFile'>
RGB
JPEG


In [ ]:
from PIL import Image
import matplotlib.pyplot as plt
image=Image.open('/content/gdrive/MyDrive/dataset/T51+T52BAD+T53BAD+T54BAD+T57BAD +T58BAD/Test/bad_dataset/DJI_0986.jpg')
print(type(image))
print(image.mode)
print(image.format)


<class 'PIL.JpegImagePlugin.JpegImageFile'>
RGB
JPEG


above images are dark images so we can apply resizing+brightness combination.


In [ ]:
from PIL import ImageEnhance
from PIL import Image
from tensorflow.keras.preprocessing.image import load_img, img_to_array
from tensorflow.keras.models import load_model
image_input=Image.open('/content/gdrive/MyDrive/dataset/T51+T52BAD+T53BAD+T54BAD+T57BAD +T58BAD/Test/bad_dataset/DJI_0489.jpg')
img_resize=image.resize((240,240))
#plt.imshow(img_resize,cmap='gray')
curr_bri=ImageEnhance.Brightness(img_resize)
new_bri=1.6
img_brightened=curr_bri.enhance(new_bri)
img = img_to_array(img_brightened)
img = img.reshape(1,240,240,3)
#print(img.shape)
#display(img_brightened)
pred=model.predict(img)
print(pred)
pred==1

1/1 [==============================] - 3s 3s/step
[[[[ 4.6561351e+00  9.2705834e-01 -6.6978117e-03 ... -2.5684336e-01
    -3.0598829e-03 -1.7290915e-03]
   [ 6.8246597e-01 -5.6121595e-02 -6.8273500e-02 ... -1.8427652e-01
    -3.2320429e-02 -1.6975254e-02]
   [-2.4506742e-01 -2.5184956e-01 -2.2431554e-01 ... -2.3388326e-01
    -1.3519891e-01 -1.0085122e-01]
   ...
   [-1.6215552e-01 -2.7428523e-01 -2.4975872e-01 ... -1.2676224e-01
    -2.1260701e-01 -2.7454302e-01]
   [-2.0218013e-01 -1.6282496e-01 -2.3377326e-01 ... -7.3560499e-02
    -2.1871541e-01 -2.6070389e-01]
   [-2.2186142e-01 -2.0283831e-02 -1.2561846e-01 ... -2.7423173e-01
    -1.0817010e-01 -1.4435104e-01]]

  [[ 1.5901058e+00 -2.7662948e-01 -5.5993922e-02 ... -2.6972669e-01
    -1.7282946e-02 -5.5802241e-03]
   [-2.7724820e-01 -2.2352897e-01 -1.8872298e-01 ... -2.3926368e-01
    -1.2458963e-01 -7.2691955e-02]
   [-1.3601556e-01 -2.2385417e-01 -2.7318063e-01 ... -1.6980307e-01
    -2.6281971e-01 -2.5634491e-01]
   ...
   [-5.

array([[[[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False]],

        [[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False]],

        [[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [False, False, False, ..., False, False, False],
         [False, False, Fa

In [ ]:
from PIL import ImageEnhance
from PIL import Image
from tensorflow.keras.preprocessing.image import load_img, img_to_array
from tensorflow.keras.models import load_model
image_input=Image.open('/content/gdrive/MyDrive/dataset/T51+T52BAD+T53BAD+T54BAD+T57BAD +T58BAD/Test/bad_dataset/DJI_0491.jpg')
img_resize=image.resize((240,240))
#plt.imshow(img_resize,cmap='gray')
curr_bri=ImageEnhance.Brightness(img_resize)
new_bri=1.6
img_brightened=curr_bri.enhance(new_bri)
img = img_to_array(img_brightened)
img = img.reshape(1,240,240,3)
#print(img.shape)
#display(img_brightened)
pred=model.predict(img)
print(pred)
pred==1


1/1 [==============================] - 0s 31ms/step
[[[[ 4.6561351e+00  9.2705834e-01 -6.6978117e-03 ... -2.5684336e-01
    -3.0598829e-03 -1.7290915e-03]
   [ 6.8246597e-01 -5.6121595e-02 -6.8273500e-02 ... -1.8427652e-01
    -3.2320429e-02 -1.6975254e-02]
   [-2.4506742e-01 -2.5184956e-01 -2.2431554e-01 ... -2.3388326e-01
    -1.3519891e-01 -1.0085122e-01]
   ...
   [-1.6215552e-01 -2.7428523e-01 -2.4975872e-01 ... -1.2676224e-01
    -2.1260701e-01 -2.7454302e-01]
   [-2.0218013e-01 -1.6282496e-01 -2.3377326e-01 ... -7.3560499e-02
    -2.1871541e-01 -2.6070389e-01]
   [-2.2186142e-01 -2.0283831e-02 -1.2561846e-01 ... -2.7423173e-01
    -1.0817010e-01 -1.4435104e-01]]

  [[ 1.5901058e+00 -2.7662948e-01 -5.5993922e-02 ... -2.6972669e-01
    -1.7282946e-02 -5.5802241e-03]
   [-2.7724820e-01 -2.2352897e-01 -1.8872298e-01 ... -2.3926368e-01
    -1.2458963e-01 -7.2691955e-02]
   [-1.3601556e-01 -2.2385417e-01 -2.7318063e-01 ... -1.6980307e-01
    -2.6281971e-01 -2.5634491e-01]
   ...
   [-

array([[[[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False]],

        [[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False]],

        [[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [False, False, False, ..., False, False, False],
         [False, False, Fa

In [ ]:
from PIL import ImageEnhance
from PIL import Image
from tensorflow.keras.preprocessing.image import load_img, img_to_array
from tensorflow.keras.models import load_model
image_input=Image.open('/content/gdrive/MyDrive/dataset/T51+T52BAD+T53BAD+T54BAD+T57BAD +T58BAD/Test/bad_dataset/DJI_0493.jpg')
img_resize=image.resize((240,240))
#plt.imshow(img_resize,cmap='gray')
curr_bri=ImageEnhance.Brightness(img_resize)
new_bri=1.6
img_brightened=curr_bri.enhance(new_bri)
img = img_to_array(img_brightened)
img = img.reshape(1,240,240,3)
#print(img.shape)
#display(img_brightened)
pred=model.predict(img)
print(pred)
pred==1

1/1 [==============================] - 0s 30ms/step
[[[[ 4.6561351e+00  9.2705834e-01 -6.6978117e-03 ... -2.5684336e-01
    -3.0598829e-03 -1.7290915e-03]
   [ 6.8246597e-01 -5.6121595e-02 -6.8273500e-02 ... -1.8427652e-01
    -3.2320429e-02 -1.6975254e-02]
   [-2.4506742e-01 -2.5184956e-01 -2.2431554e-01 ... -2.3388326e-01
    -1.3519891e-01 -1.0085122e-01]
   ...
   [-1.6215552e-01 -2.7428523e-01 -2.4975872e-01 ... -1.2676224e-01
    -2.1260701e-01 -2.7454302e-01]
   [-2.0218013e-01 -1.6282496e-01 -2.3377326e-01 ... -7.3560499e-02
    -2.1871541e-01 -2.6070389e-01]
   [-2.2186142e-01 -2.0283831e-02 -1.2561846e-01 ... -2.7423173e-01
    -1.0817010e-01 -1.4435104e-01]]

  [[ 1.5901058e+00 -2.7662948e-01 -5.5993922e-02 ... -2.6972669e-01
    -1.7282946e-02 -5.5802241e-03]
   [-2.7724820e-01 -2.2352897e-01 -1.8872298e-01 ... -2.3926368e-01
    -1.2458963e-01 -7.2691955e-02]
   [-1.3601556e-01 -2.2385417e-01 -2.7318063e-01 ... -1.6980307e-01
    -2.6281971e-01 -2.5634491e-01]
   ...
   [-

array([[[[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False]],

        [[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False]],

        [[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [False, False, False, ..., False, False, False],
         [False, False, Fa

In [ ]:
from PIL import ImageEnhance
from PIL import Image
from tensorflow.keras.preprocessing.image import load_img, img_to_array
from tensorflow.keras.models import load_model
image_input=Image.open('/content/gdrive/MyDrive/dataset/T51+T52BAD+T53BAD+T54BAD+T57BAD +T58BAD/Test/bad_dataset/DJI_0495.jpg')
img_resize=image.resize((240,240))
#plt.imshow(img_resize,cmap='gray')
curr_bri=ImageEnhance.Brightness(img_resize)
new_bri=1.6
img_brightened=curr_bri.enhance(new_bri)
img = img_to_array(img_brightened)
img = img.reshape(1,240,240,3)
#print(img.shape)
#display(img_brightened)
pred=model.predict(img)
print(pred)
pred==1

1/1 [==============================] - 0s 28ms/step
[[[[ 4.6561351e+00  9.2705834e-01 -6.6978117e-03 ... -2.5684336e-01
    -3.0598829e-03 -1.7290915e-03]
   [ 6.8246597e-01 -5.6121595e-02 -6.8273500e-02 ... -1.8427652e-01
    -3.2320429e-02 -1.6975254e-02]
   [-2.4506742e-01 -2.5184956e-01 -2.2431554e-01 ... -2.3388326e-01
    -1.3519891e-01 -1.0085122e-01]
   ...
   [-1.6215552e-01 -2.7428523e-01 -2.4975872e-01 ... -1.2676224e-01
    -2.1260701e-01 -2.7454302e-01]
   [-2.0218013e-01 -1.6282496e-01 -2.3377326e-01 ... -7.3560499e-02
    -2.1871541e-01 -2.6070389e-01]
   [-2.2186142e-01 -2.0283831e-02 -1.2561846e-01 ... -2.7423173e-01
    -1.0817010e-01 -1.4435104e-01]]

  [[ 1.5901058e+00 -2.7662948e-01 -5.5993922e-02 ... -2.6972669e-01
    -1.7282946e-02 -5.5802241e-03]
   [-2.7724820e-01 -2.2352897e-01 -1.8872298e-01 ... -2.3926368e-01
    -1.2458963e-01 -7.2691955e-02]
   [-1.3601556e-01 -2.2385417e-01 -2.7318063e-01 ... -1.6980307e-01
    -2.6281971e-01 -2.5634491e-01]
   ...
   [-

array([[[[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False]],

        [[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False]],

        [[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [False, False, False, ..., False, False, False],
         [False, False, Fa

In [ ]:
from PIL import ImageEnhance
from PIL import Image
from tensorflow.keras.preprocessing.image import load_img, img_to_array
from tensorflow.keras.models import load_model
image_input=Image.open('/content/gdrive/MyDrive/dataset/T51+T52BAD+T53BAD+T54BAD+T57BAD +T58BAD/Test/bad_dataset/DJI_0497.jpg')
img_resize=image.resize((240,240))
#plt.imshow(img_resize,cmap='gray')
curr_bri=ImageEnhance.Brightness(img_resize)
new_bri=1.6
img_brightened=curr_bri.enhance(new_bri)
img = img_to_array(img_brightened)
img = img.reshape(1,240,240,3)
#print(img.shape)
#display(img_brightened)
pred=model.predict(img)
print(pred)
pred==1

1/1 [==============================] - 0s 42ms/step
[[[[ 4.6561351e+00  9.2705834e-01 -6.6978117e-03 ... -2.5684336e-01
    -3.0598829e-03 -1.7290915e-03]
   [ 6.8246597e-01 -5.6121595e-02 -6.8273500e-02 ... -1.8427652e-01
    -3.2320429e-02 -1.6975254e-02]
   [-2.4506742e-01 -2.5184956e-01 -2.2431554e-01 ... -2.3388326e-01
    -1.3519891e-01 -1.0085122e-01]
   ...
   [-1.6215552e-01 -2.7428523e-01 -2.4975872e-01 ... -1.2676224e-01
    -2.1260701e-01 -2.7454302e-01]
   [-2.0218013e-01 -1.6282496e-01 -2.3377326e-01 ... -7.3560499e-02
    -2.1871541e-01 -2.6070389e-01]
   [-2.2186142e-01 -2.0283831e-02 -1.2561846e-01 ... -2.7423173e-01
    -1.0817010e-01 -1.4435104e-01]]

  [[ 1.5901058e+00 -2.7662948e-01 -5.5993922e-02 ... -2.6972669e-01
    -1.7282946e-02 -5.5802241e-03]
   [-2.7724820e-01 -2.2352897e-01 -1.8872298e-01 ... -2.3926368e-01
    -1.2458963e-01 -7.2691955e-02]
   [-1.3601556e-01 -2.2385417e-01 -2.7318063e-01 ... -1.6980307e-01
    -2.6281971e-01 -2.5634491e-01]
   ...
   [-

array([[[[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False]],

        [[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False]],

        [[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [False, False, False, ..., False, False, False],
         [False, False, Fa

In [ ]:
from PIL import ImageEnhance
from PIL import Image
from tensorflow.keras.preprocessing.image import load_img, img_to_array
from tensorflow.keras.models import load_model
image_input=Image.open('/content/gdrive/MyDrive/dataset/T51+T52BAD+T53BAD+T54BAD+T57BAD +T58BAD/Test/bad_dataset/DJI_0501.jpg')
img_resize=image.resize((240,240))
#plt.imshow(img_resize,cmap='gray')
curr_bri=ImageEnhance.Brightness(img_resize)
new_bri=1.6
img_brightened=curr_bri.enhance(new_bri)
img = img_to_array(img_brightened)
img = img.reshape(1,240,240,3)
#print(img.shape)
#display(img_brightened)
pred=model.predict(img)
print(pred)
pred==1

1/1 [==============================] - 0s 27ms/step
[[[[ 4.6561351e+00  9.2705834e-01 -6.6978117e-03 ... -2.5684336e-01
    -3.0598829e-03 -1.7290915e-03]
   [ 6.8246597e-01 -5.6121595e-02 -6.8273500e-02 ... -1.8427652e-01
    -3.2320429e-02 -1.6975254e-02]
   [-2.4506742e-01 -2.5184956e-01 -2.2431554e-01 ... -2.3388326e-01
    -1.3519891e-01 -1.0085122e-01]
   ...
   [-1.6215552e-01 -2.7428523e-01 -2.4975872e-01 ... -1.2676224e-01
    -2.1260701e-01 -2.7454302e-01]
   [-2.0218013e-01 -1.6282496e-01 -2.3377326e-01 ... -7.3560499e-02
    -2.1871541e-01 -2.6070389e-01]
   [-2.2186142e-01 -2.0283831e-02 -1.2561846e-01 ... -2.7423173e-01
    -1.0817010e-01 -1.4435104e-01]]

  [[ 1.5901058e+00 -2.7662948e-01 -5.5993922e-02 ... -2.6972669e-01
    -1.7282946e-02 -5.5802241e-03]
   [-2.7724820e-01 -2.2352897e-01 -1.8872298e-01 ... -2.3926368e-01
    -1.2458963e-01 -7.2691955e-02]
   [-1.3601556e-01 -2.2385417e-01 -2.7318063e-01 ... -1.6980307e-01
    -2.6281971e-01 -2.5634491e-01]
   ...
   [-

array([[[[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False]],

        [[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False]],

        [[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [False, False, False, ..., False, False, False],
         [False, False, Fa

In [ ]:
from PIL import ImageEnhance
from PIL import Image
from tensorflow.keras.preprocessing.image import load_img, img_to_array
from tensorflow.keras.models import load_model
image_input=Image.open('/content/gdrive/MyDrive/dataset/T51+T52BAD+T53BAD+T54BAD+T57BAD +T58BAD/Test/bad_dataset/DJI_0503.jpg')
img_resize=image.resize((240,240))
#plt.imshow(img_resize,cmap='gray')
curr_bri=ImageEnhance.Brightness(img_resize)
new_bri=1.6
img_brightened=curr_bri.enhance(new_bri)
img = img_to_array(img_brightened)
img = img.reshape(1,240,240,3)
#print(img.shape)
#display(img_brightened)
pred=model.predict(img)
print(pred)
pred==1

1/1 [==============================] - 0s 30ms/step
[[[[ 4.6561351e+00  9.2705834e-01 -6.6978117e-03 ... -2.5684336e-01
    -3.0598829e-03 -1.7290915e-03]
   [ 6.8246597e-01 -5.6121595e-02 -6.8273500e-02 ... -1.8427652e-01
    -3.2320429e-02 -1.6975254e-02]
   [-2.4506742e-01 -2.5184956e-01 -2.2431554e-01 ... -2.3388326e-01
    -1.3519891e-01 -1.0085122e-01]
   ...
   [-1.6215552e-01 -2.7428523e-01 -2.4975872e-01 ... -1.2676224e-01
    -2.1260701e-01 -2.7454302e-01]
   [-2.0218013e-01 -1.6282496e-01 -2.3377326e-01 ... -7.3560499e-02
    -2.1871541e-01 -2.6070389e-01]
   [-2.2186142e-01 -2.0283831e-02 -1.2561846e-01 ... -2.7423173e-01
    -1.0817010e-01 -1.4435104e-01]]

  [[ 1.5901058e+00 -2.7662948e-01 -5.5993922e-02 ... -2.6972669e-01
    -1.7282946e-02 -5.5802241e-03]
   [-2.7724820e-01 -2.2352897e-01 -1.8872298e-01 ... -2.3926368e-01
    -1.2458963e-01 -7.2691955e-02]
   [-1.3601556e-01 -2.2385417e-01 -2.7318063e-01 ... -1.6980307e-01
    -2.6281971e-01 -2.5634491e-01]
   ...
   [-

array([[[[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False]],

        [[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False]],

        [[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [False, False, False, ..., False, False, False],
         [False, False, Fa

In [ ]:
from PIL import ImageEnhance
from PIL import Image
from tensorflow.keras.preprocessing.image import load_img, img_to_array
from tensorflow.keras.models import load_model
image_input=Image.open('/content/gdrive/MyDrive/dataset/T51+T52BAD+T53BAD+T54BAD+T57BAD +T58BAD/Test/bad_dataset/DJI_0505.jpg')
img_resize=image.resize((240,240))
#plt.imshow(img_resize,cmap='gray')
curr_bri=ImageEnhance.Brightness(img_resize)
new_bri=1.6
img_brightened=curr_bri.enhance(new_bri)
img = img_to_array(img_brightened)
img = img.reshape(1,240,240,3)
#print(img.shape)
#display(img_brightened)
pred=model.predict(img)
print(pred)
pred==1

1/1 [==============================] - 0s 30ms/step
[[[[ 4.6561351e+00  9.2705834e-01 -6.6978117e-03 ... -2.5684336e-01
    -3.0598829e-03 -1.7290915e-03]
   [ 6.8246597e-01 -5.6121595e-02 -6.8273500e-02 ... -1.8427652e-01
    -3.2320429e-02 -1.6975254e-02]
   [-2.4506742e-01 -2.5184956e-01 -2.2431554e-01 ... -2.3388326e-01
    -1.3519891e-01 -1.0085122e-01]
   ...
   [-1.6215552e-01 -2.7428523e-01 -2.4975872e-01 ... -1.2676224e-01
    -2.1260701e-01 -2.7454302e-01]
   [-2.0218013e-01 -1.6282496e-01 -2.3377326e-01 ... -7.3560499e-02
    -2.1871541e-01 -2.6070389e-01]
   [-2.2186142e-01 -2.0283831e-02 -1.2561846e-01 ... -2.7423173e-01
    -1.0817010e-01 -1.4435104e-01]]

  [[ 1.5901058e+00 -2.7662948e-01 -5.5993922e-02 ... -2.6972669e-01
    -1.7282946e-02 -5.5802241e-03]
   [-2.7724820e-01 -2.2352897e-01 -1.8872298e-01 ... -2.3926368e-01
    -1.2458963e-01 -7.2691955e-02]
   [-1.3601556e-01 -2.2385417e-01 -2.7318063e-01 ... -1.6980307e-01
    -2.6281971e-01 -2.5634491e-01]
   ...
   [-

array([[[[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False]],

        [[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False]],

        [[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [False, False, False, ..., False, False, False],
         [False, False, Fa

In [ ]:
from PIL import ImageEnhance
from PIL import Image
from tensorflow.keras.preprocessing.image import load_img, img_to_array
from tensorflow.keras.models import load_model
image_input=Image.open('/content/gdrive/MyDrive/dataset/T51+T52BAD+T53BAD+T54BAD+T57BAD +T58BAD/Test/bad_dataset/DJI_0507.jpg')
img_resize=image.resize((240,240))
#plt.imshow(img_resize,cmap='gray')
curr_bri=ImageEnhance.Brightness(img_resize)
new_bri=1.6
img_brightened=curr_bri.enhance(new_bri)
img = img_to_array(img_brightened)
img = img.reshape(1,240,240,3)
#print(img.shape)
#display(img_brightened)
pred=model.predict(img)
print(pred)
pred==1

1/1 [==============================] - 0s 43ms/step
[[[[ 4.6561351e+00  9.2705834e-01 -6.6978117e-03 ... -2.5684336e-01
    -3.0598829e-03 -1.7290915e-03]
   [ 6.8246597e-01 -5.6121595e-02 -6.8273500e-02 ... -1.8427652e-01
    -3.2320429e-02 -1.6975254e-02]
   [-2.4506742e-01 -2.5184956e-01 -2.2431554e-01 ... -2.3388326e-01
    -1.3519891e-01 -1.0085122e-01]
   ...
   [-1.6215552e-01 -2.7428523e-01 -2.4975872e-01 ... -1.2676224e-01
    -2.1260701e-01 -2.7454302e-01]
   [-2.0218013e-01 -1.6282496e-01 -2.3377326e-01 ... -7.3560499e-02
    -2.1871541e-01 -2.6070389e-01]
   [-2.2186142e-01 -2.0283831e-02 -1.2561846e-01 ... -2.7423173e-01
    -1.0817010e-01 -1.4435104e-01]]

  [[ 1.5901058e+00 -2.7662948e-01 -5.5993922e-02 ... -2.6972669e-01
    -1.7282946e-02 -5.5802241e-03]
   [-2.7724820e-01 -2.2352897e-01 -1.8872298e-01 ... -2.3926368e-01
    -1.2458963e-01 -7.2691955e-02]
   [-1.3601556e-01 -2.2385417e-01 -2.7318063e-01 ... -1.6980307e-01
    -2.6281971e-01 -2.5634491e-01]
   ...
   [-

array([[[[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False]],

        [[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False]],

        [[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [False, False, False, ..., False, False, False],
         [False, False, Fa

In [ ]:
from PIL import ImageEnhance
from PIL import Image
from tensorflow.keras.preprocessing.image import load_img, img_to_array
from tensorflow.keras.models import load_model
image_input=Image.open('/content/gdrive/MyDrive/dataset/T51+T52BAD+T53BAD+T54BAD+T57BAD +T58BAD/Test/bad_dataset/DJI_0509.jpg')
img_resize=image.resize((240,240))
#plt.imshow(img_resize,cmap='gray')
curr_bri=ImageEnhance.Brightness(img_resize)
new_bri=1.6
img_brightened=curr_bri.enhance(new_bri)
img = img_to_array(img_brightened)
img = img.reshape(1,240,240,3)
#print(img.shape)
#display(img_brightened)
pred=model.predict(img)
print(pred)
pred==1

1/1 [==============================] - 0s 43ms/step
[[[[ 4.6561351e+00  9.2705834e-01 -6.6978117e-03 ... -2.5684336e-01
    -3.0598829e-03 -1.7290915e-03]
   [ 6.8246597e-01 -5.6121595e-02 -6.8273500e-02 ... -1.8427652e-01
    -3.2320429e-02 -1.6975254e-02]
   [-2.4506742e-01 -2.5184956e-01 -2.2431554e-01 ... -2.3388326e-01
    -1.3519891e-01 -1.0085122e-01]
   ...
   [-1.6215552e-01 -2.7428523e-01 -2.4975872e-01 ... -1.2676224e-01
    -2.1260701e-01 -2.7454302e-01]
   [-2.0218013e-01 -1.6282496e-01 -2.3377326e-01 ... -7.3560499e-02
    -2.1871541e-01 -2.6070389e-01]
   [-2.2186142e-01 -2.0283831e-02 -1.2561846e-01 ... -2.7423173e-01
    -1.0817010e-01 -1.4435104e-01]]

  [[ 1.5901058e+00 -2.7662948e-01 -5.5993922e-02 ... -2.6972669e-01
    -1.7282946e-02 -5.5802241e-03]
   [-2.7724820e-01 -2.2352897e-01 -1.8872298e-01 ... -2.3926368e-01
    -1.2458963e-01 -7.2691955e-02]
   [-1.3601556e-01 -2.2385417e-01 -2.7318063e-01 ... -1.6980307e-01
    -2.6281971e-01 -2.5634491e-01]
   ...
   [-

array([[[[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False]],

        [[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False]],

        [[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [False, False, False, ..., False, False, False],
         [False, False, Fa

In [ ]:
from PIL import ImageEnhance
from PIL import Image
from tensorflow.keras.preprocessing.image import load_img, img_to_array
from tensorflow.keras.models import load_model
image_input=Image.open('/content/gdrive/MyDrive/dataset/T51+T52BAD+T53BAD+T54BAD+T57BAD +T58BAD/Test/bad_dataset/DJI_0976.jpg')
img_resize=image.resize((240,240))
#plt.imshow(img_resize,cmap='gray')
curr_bri=ImageEnhance.Brightness(img_resize)
new_bri=1.6
img_brightened=curr_bri.enhance(new_bri)
img = img_to_array(img_brightened)
img = img.reshape(1,240,240,3)
#print(img.shape)
#display(img_brightened)
pred=model.predict(img)
print(pred)
pred==1

1/1 [==============================] - 0s 41ms/step
[[[[ 4.6561351e+00  9.2705834e-01 -6.6978117e-03 ... -2.5684336e-01
    -3.0598829e-03 -1.7290915e-03]
   [ 6.8246597e-01 -5.6121595e-02 -6.8273500e-02 ... -1.8427652e-01
    -3.2320429e-02 -1.6975254e-02]
   [-2.4506742e-01 -2.5184956e-01 -2.2431554e-01 ... -2.3388326e-01
    -1.3519891e-01 -1.0085122e-01]
   ...
   [-1.6215552e-01 -2.7428523e-01 -2.4975872e-01 ... -1.2676224e-01
    -2.1260701e-01 -2.7454302e-01]
   [-2.0218013e-01 -1.6282496e-01 -2.3377326e-01 ... -7.3560499e-02
    -2.1871541e-01 -2.6070389e-01]
   [-2.2186142e-01 -2.0283831e-02 -1.2561846e-01 ... -2.7423173e-01
    -1.0817010e-01 -1.4435104e-01]]

  [[ 1.5901058e+00 -2.7662948e-01 -5.5993922e-02 ... -2.6972669e-01
    -1.7282946e-02 -5.5802241e-03]
   [-2.7724820e-01 -2.2352897e-01 -1.8872298e-01 ... -2.3926368e-01
    -1.2458963e-01 -7.2691955e-02]
   [-1.3601556e-01 -2.2385417e-01 -2.7318063e-01 ... -1.6980307e-01
    -2.6281971e-01 -2.5634491e-01]
   ...
   [-

array([[[[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False]],

        [[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False]],

        [[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [False, False, False, ..., False, False, False],
         [False, False, Fa

In [ ]:
from PIL import ImageEnhance
from PIL import Image
from tensorflow.keras.preprocessing.image import load_img, img_to_array
from tensorflow.keras.models import load_model
image_input=Image.open('/content/gdrive/MyDrive/dataset/T51+T52BAD+T53BAD+T54BAD+T57BAD +T58BAD/Test/bad_dataset/DJI_0978.jpg')
img_resize=image.resize((240,240))
#plt.imshow(img_resize,cmap='gray')
curr_bri=ImageEnhance.Brightness(img_resize)
new_bri=1.6
img_brightened=curr_bri.enhance(new_bri)
img = img_to_array(img_brightened)
img = img.reshape(1,240,240,3)
#print(img.shape)
#display(img_brightened)
pred=model.predict(img)
print(pred)
pred==1

1/1 [==============================] - 0s 38ms/step
[[[[ 4.6561351e+00  9.2705834e-01 -6.6978117e-03 ... -2.5684336e-01
    -3.0598829e-03 -1.7290915e-03]
   [ 6.8246597e-01 -5.6121595e-02 -6.8273500e-02 ... -1.8427652e-01
    -3.2320429e-02 -1.6975254e-02]
   [-2.4506742e-01 -2.5184956e-01 -2.2431554e-01 ... -2.3388326e-01
    -1.3519891e-01 -1.0085122e-01]
   ...
   [-1.6215552e-01 -2.7428523e-01 -2.4975872e-01 ... -1.2676224e-01
    -2.1260701e-01 -2.7454302e-01]
   [-2.0218013e-01 -1.6282496e-01 -2.3377326e-01 ... -7.3560499e-02
    -2.1871541e-01 -2.6070389e-01]
   [-2.2186142e-01 -2.0283831e-02 -1.2561846e-01 ... -2.7423173e-01
    -1.0817010e-01 -1.4435104e-01]]

  [[ 1.5901058e+00 -2.7662948e-01 -5.5993922e-02 ... -2.6972669e-01
    -1.7282946e-02 -5.5802241e-03]
   [-2.7724820e-01 -2.2352897e-01 -1.8872298e-01 ... -2.3926368e-01
    -1.2458963e-01 -7.2691955e-02]
   [-1.3601556e-01 -2.2385417e-01 -2.7318063e-01 ... -1.6980307e-01
    -2.6281971e-01 -2.5634491e-01]
   ...
   [-

array([[[[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False]],

        [[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False]],

        [[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [False, False, False, ..., False, False, False],
         [False, False, Fa

In [ ]:
from PIL import ImageEnhance
from PIL import Image
from tensorflow.keras.preprocessing.image import load_img, img_to_array
from tensorflow.keras.models import load_model
image_input=Image.open('/content/gdrive/MyDrive/dataset/T51+T52BAD+T53BAD+T54BAD+T57BAD +T58BAD/Test/bad_dataset/DJI_0980.jpg')
img_resize=image.resize((240,240))
#plt.imshow(img_resize,cmap='gray')
curr_bri=ImageEnhance.Brightness(img_resize)
new_bri=1.6
img_brightened=curr_bri.enhance(new_bri)
img = img_to_array(img_brightened)
img = img.reshape(1,240,240,3)
#print(img.shape)
#display(img_brightened)
pred=model.predict(img)
print(pred)
pred==1

1/1 [==============================] - 0s 34ms/step
[[[[ 4.6561351e+00  9.2705834e-01 -6.6978117e-03 ... -2.5684336e-01
    -3.0598829e-03 -1.7290915e-03]
   [ 6.8246597e-01 -5.6121595e-02 -6.8273500e-02 ... -1.8427652e-01
    -3.2320429e-02 -1.6975254e-02]
   [-2.4506742e-01 -2.5184956e-01 -2.2431554e-01 ... -2.3388326e-01
    -1.3519891e-01 -1.0085122e-01]
   ...
   [-1.6215552e-01 -2.7428523e-01 -2.4975872e-01 ... -1.2676224e-01
    -2.1260701e-01 -2.7454302e-01]
   [-2.0218013e-01 -1.6282496e-01 -2.3377326e-01 ... -7.3560499e-02
    -2.1871541e-01 -2.6070389e-01]
   [-2.2186142e-01 -2.0283831e-02 -1.2561846e-01 ... -2.7423173e-01
    -1.0817010e-01 -1.4435104e-01]]

  [[ 1.5901058e+00 -2.7662948e-01 -5.5993922e-02 ... -2.6972669e-01
    -1.7282946e-02 -5.5802241e-03]
   [-2.7724820e-01 -2.2352897e-01 -1.8872298e-01 ... -2.3926368e-01
    -1.2458963e-01 -7.2691955e-02]
   [-1.3601556e-01 -2.2385417e-01 -2.7318063e-01 ... -1.6980307e-01
    -2.6281971e-01 -2.5634491e-01]
   ...
   [-

array([[[[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False]],

        [[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False]],

        [[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [False, False, False, ..., False, False, False],
         [False, False, Fa

In [ ]:
from PIL import ImageEnhance
from PIL import Image
from tensorflow.keras.preprocessing.image import load_img, img_to_array
from tensorflow.keras.models import load_model
image_input=Image.open('/content/gdrive/MyDrive/dataset/T51+T52BAD+T53BAD+T54BAD+T57BAD +T58BAD/Test/bad_dataset/DJI_0982.jpg')
img_resize=image.resize((240,240))
#plt.imshow(img_resize,cmap='gray')
curr_bri=ImageEnhance.Brightness(img_resize)
new_bri=1.6
img_brightened=curr_bri.enhance(new_bri)
img = img_to_array(img_brightened)
img = img.reshape(1,240,240,3)
#print(img.shape)
#display(img_brightened)
pred=model.predict(img)
print(pred)
pred==1

1/1 [==============================] - 0s 27ms/step
[[[[ 4.6561351e+00  9.2705834e-01 -6.6978117e-03 ... -2.5684336e-01
    -3.0598829e-03 -1.7290915e-03]
   [ 6.8246597e-01 -5.6121595e-02 -6.8273500e-02 ... -1.8427652e-01
    -3.2320429e-02 -1.6975254e-02]
   [-2.4506742e-01 -2.5184956e-01 -2.2431554e-01 ... -2.3388326e-01
    -1.3519891e-01 -1.0085122e-01]
   ...
   [-1.6215552e-01 -2.7428523e-01 -2.4975872e-01 ... -1.2676224e-01
    -2.1260701e-01 -2.7454302e-01]
   [-2.0218013e-01 -1.6282496e-01 -2.3377326e-01 ... -7.3560499e-02
    -2.1871541e-01 -2.6070389e-01]
   [-2.2186142e-01 -2.0283831e-02 -1.2561846e-01 ... -2.7423173e-01
    -1.0817010e-01 -1.4435104e-01]]

  [[ 1.5901058e+00 -2.7662948e-01 -5.5993922e-02 ... -2.6972669e-01
    -1.7282946e-02 -5.5802241e-03]
   [-2.7724820e-01 -2.2352897e-01 -1.8872298e-01 ... -2.3926368e-01
    -1.2458963e-01 -7.2691955e-02]
   [-1.3601556e-01 -2.2385417e-01 -2.7318063e-01 ... -1.6980307e-01
    -2.6281971e-01 -2.5634491e-01]
   ...
   [-

array([[[[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False]],

        [[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False]],

        [[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [False, False, False, ..., False, False, False],
         [False, False, Fa

In [ ]:
from PIL import ImageEnhance
from PIL import Image
from tensorflow.keras.preprocessing.image import load_img, img_to_array
from tensorflow.keras.models import load_model
image_input=Image.open('/content/gdrive/MyDrive/dataset/T51+T52BAD+T53BAD+T54BAD+T57BAD +T58BAD/Test/bad_dataset/DJI_0984.jpg')
img_resize=image.resize((240,240))
#plt.imshow(img_resize,cmap='gray')
curr_bri=ImageEnhance.Brightness(img_resize)
new_bri=1.6
img_brightened=curr_bri.enhance(new_bri)
img = img_to_array(img_brightened)
img = img.reshape(1,240,240,3)
#print(img.shape)
#display(img_brightened)
pred=model.predict(img)
print(pred)
pred==1

1/1 [==============================] - 0s 29ms/step
[[[[ 4.6561351e+00  9.2705834e-01 -6.6978117e-03 ... -2.5684336e-01
    -3.0598829e-03 -1.7290915e-03]
   [ 6.8246597e-01 -5.6121595e-02 -6.8273500e-02 ... -1.8427652e-01
    -3.2320429e-02 -1.6975254e-02]
   [-2.4506742e-01 -2.5184956e-01 -2.2431554e-01 ... -2.3388326e-01
    -1.3519891e-01 -1.0085122e-01]
   ...
   [-1.6215552e-01 -2.7428523e-01 -2.4975872e-01 ... -1.2676224e-01
    -2.1260701e-01 -2.7454302e-01]
   [-2.0218013e-01 -1.6282496e-01 -2.3377326e-01 ... -7.3560499e-02
    -2.1871541e-01 -2.6070389e-01]
   [-2.2186142e-01 -2.0283831e-02 -1.2561846e-01 ... -2.7423173e-01
    -1.0817010e-01 -1.4435104e-01]]

  [[ 1.5901058e+00 -2.7662948e-01 -5.5993922e-02 ... -2.6972669e-01
    -1.7282946e-02 -5.5802241e-03]
   [-2.7724820e-01 -2.2352897e-01 -1.8872298e-01 ... -2.3926368e-01
    -1.2458963e-01 -7.2691955e-02]
   [-1.3601556e-01 -2.2385417e-01 -2.7318063e-01 ... -1.6980307e-01
    -2.6281971e-01 -2.5634491e-01]
   ...
   [-

array([[[[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False]],

        [[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False]],

        [[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [False, False, False, ..., False, False, False],
         [False, False, Fa

In [ ]:
from PIL import ImageEnhance
from PIL import Image
from tensorflow.keras.preprocessing.image import load_img, img_to_array
from tensorflow.keras.models import load_model
image_input=Image.open('/content/gdrive/MyDrive/dataset/T51+T52BAD+T53BAD+T54BAD+T57BAD +T58BAD/Test/bad_dataset/DJI_0986.jpg')
img_resize=image.resize((240,240))
#plt.imshow(img_resize,cmap='gray')
curr_bri=ImageEnhance.Brightness(img_resize)
new_bri=1.6
img_brightened=curr_bri.enhance(new_bri)
img = img_to_array(img_brightened)
img = img.reshape(1,240,240,3)
#print(img.shape)
#display(img_brightened)
pred=model.predict(img)
print(pred)
pred==1

1/1 [==============================] - 0s 28ms/step
[[[[ 4.6561351e+00  9.2705834e-01 -6.6978117e-03 ... -2.5684336e-01
    -3.0598829e-03 -1.7290915e-03]
   [ 6.8246597e-01 -5.6121595e-02 -6.8273500e-02 ... -1.8427652e-01
    -3.2320429e-02 -1.6975254e-02]
   [-2.4506742e-01 -2.5184956e-01 -2.2431554e-01 ... -2.3388326e-01
    -1.3519891e-01 -1.0085122e-01]
   ...
   [-1.6215552e-01 -2.7428523e-01 -2.4975872e-01 ... -1.2676224e-01
    -2.1260701e-01 -2.7454302e-01]
   [-2.0218013e-01 -1.6282496e-01 -2.3377326e-01 ... -7.3560499e-02
    -2.1871541e-01 -2.6070389e-01]
   [-2.2186142e-01 -2.0283831e-02 -1.2561846e-01 ... -2.7423173e-01
    -1.0817010e-01 -1.4435104e-01]]

  [[ 1.5901058e+00 -2.7662948e-01 -5.5993922e-02 ... -2.6972669e-01
    -1.7282946e-02 -5.5802241e-03]
   [-2.7724820e-01 -2.2352897e-01 -1.8872298e-01 ... -2.3926368e-01
    -1.2458963e-01 -7.2691955e-02]
   [-1.3601556e-01 -2.2385417e-01 -2.7318063e-01 ... -1.6980307e-01
    -2.6281971e-01 -2.5634491e-01]
   ...
   [-

array([[[[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False]],

        [[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False]],

        [[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [False, False, False, ..., False, False, False],
         [False, False, Fa

In [ ]:
from sklearn.metrics import classification_report,confusion_matrix
truth=['bad','bad','bad','bad','bad','bad','bad','bad','bad','bad','bad','bad','bad','bad','bad','bad','bad','bad','bad','bad','bad','bad','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good']
prediction=['bad','bad','bad','bad','bad','bad','bad','bad','bad','bad','bad','bad','bad','bad','bad','bad','bad','bad','bad','bad','bad','bad','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good','good']
print(classification_report(truth,prediction))
print(confusion_matrix(truth,prediction))

              precision    recall  f1-score   support

         bad       1.00      1.00      1.00        22
        good       1.00      1.00      1.00        64

    accuracy                           1.00        86
   macro avg       1.00      1.00      1.00        86
weighted avg       1.00      1.00      1.00        86

[[22  0]
 [ 0 64]]
